### ISSUE TITLE
Handle the following errors

### ISSUE THREAD

**Issue by llacroix** [llacroix/prometheus-swarm-discovery#1]
```
prometheus-sd.1.gn54x74aj929@ns307587    | 2019-12-31 04:33:34,847 - __main__ - INFO - Configuration updated in /configs/http/file_sd.json
prometheus-sd.1.gn54x74aj929@ns307587    | Task exception was never retrieved
prometheus-sd.1.gn54x74aj929@ns307587    | future: <Task finished coro=<save_configs() done, defined at /service.py:76> exception=KeyError('ContainerStatus',)>
prometheus-sd.1.gn54x74aj929@ns307587    | Traceback (most recent call last):
prometheus-sd.1.gn54x74aj929@ns307587    |   File "/service.py", line 81, in save_configs
prometheus-sd.1.gn54x74aj929@ns307587    |     configs = await load_existing_services(docker)
prometheus-sd.1.gn54x74aj929@ns307587    |   File "/service.py", line 52, in load_existing_services
prometheus-sd.1.gn54x74aj929@ns307587    |     container_id = task['Status']['ContainerStatus']['ContainerID']
prometheus-sd.1.gn54x74aj929@ns307587    | KeyError: 'ContainerStatus'
prometheus-sd.1.gn54x74aj929@ns307587    | 2019-12-31 04:33:36,179 - __main__ - INFO - Configuration updated in /configs/http/file_sd.json
prometheus-sd.1.gn54x74aj929@ns307587    | 2019-12-31 04:34:38,860 - __main__ - INFO - Configuration updated in /configs/http/file_sd.json
prometheus-sd.1.gn54x74aj929@ns307587    | 2019-12-31 04:34:39,615 - __main__ - INFO - Configuration updated in /configs/http/file_sd.json
prometheus-sd.1.gn54x74aj929@ns307587    | 2019-12-31 04:38:45,853 - __main__ - INFO - Configuration updated in /configs/http/file_sd.json
prometheus-sd.1.gn54x74aj929@ns307587    | 2019-12-31 04:38:50,351 - __main__ - INFO - Configuration updated in /configs/http/file_sd.json
prometheus-sd.1.gn54x74aj929@ns307587    | Unclosed client session
prometheus-sd.1.gn54x74aj929@ns307587    | client_session: <aiohttp.client.ClientSession object at 0x7f922cfd2198>
prometheus-sd.1.gn54x74aj929@ns307587    | 2019-12-31 04:41:39,457 - __main__ - INFO - Configuration updated in /configs/http/file_sd.json

```

**Comment by llacroix** [comment]
It doesn't make the service crash but it should be handled to prevent actual issues

**Comment by llacroix** [comment]
Should be fixed
